import { PrismaClient } from '@prisma/client';
import { ContactMessage } from '@/src/domain/entities/ContactMessage';
import { IContactRepository } from '@/src/domain/repositories/IContactRepository';

export class PrismaContactRepository implements IContactRepository {
    constructor(private readonly prisma: PrismaClient) { }

    async create(data: Omit<ContactMessage, 'id' | 'createdAt'>): Promise<ContactMessage> {
        // contactMessage is correctly generated by Prisma from the ContactMessage model
        const contact = await this.prisma.contactMessage.create({
            data: {
                name: data.name,
                email: data.email,
                phone: data.phone,
                description: data.description,
            },
        });

        return new ContactMessage(
            contact.id,
            contact.name,
            contact.email,
            contact.description,
            contact.createdAt,
            contact.phone ?? undefined,
        );
    }

    async findAll(): Promise<ContactMessage[]> {
        const contacts = await this.prisma.contactMessage.findMany({
            orderBy: { createdAt: 'desc' },
        });

        return contacts.map(
            (contact) =>
                new ContactMessage(
                    contact.id,
                    contact.name,
                    contact.email,
                    contact.description,
                    contact.createdAt,
                    contact.phone ?? undefined,
                ),
        );
    }
}
